# Generated by Django 2.2.16 on 2020-10-10 09:30

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('name_suffix', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=50, region=None)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoanInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('type_a', 'Type A'), ('type_b', 'Type B')], max_length=254)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monthly_amortization', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('loan_term', models.PositiveIntegerField()),
                ('total_sum_of_payments', models.DecimalField(decimal_places=2, max_digits=18)),
                ('first_loan_payment_date', models.DateField()),
                ('loan_maturity_date', models.DateField()),
                ('customer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_calculator.CustomerInfo')),
            ],
        ),
    ]
