# Generated by Django 2.2.16 on 2020-10-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerinfo',
            unique_together={('first_name', 'last_name', 'email', 'phone_number', 'city', 'province')},
        ),
    ]
